Data Wrongling:- Converting data one format to another format

*feature transormation
*feature scaling
*feature encoding

**FEATURE SCALING**

Two types scaling
*Normalization:- Convering all values <=1
*Standerdization:-Convering all values to correspondness Zscore

***Standerdization*** : z=(x-x_mean)/std

In [4]:
import pandas as pd
df=pd.DataFrame({"x":[1,2,3,4,5]})
df

   x
0  1
1  2
2  3
3  4
4  5

***Standerdization using standerd scalar in sklearn***

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df['x_sc_sk']=sc.fit_transform(df[['x']])
df

   x   x_sc_sk
0  1 -1.414214
1  2 -0.707107
2  3  0.000000
3  4  0.707107
4  5  1.414214

***Standerdization using pandas***

In [16]:
df['x'].mean()

3.0

In [18]:
df['x'].std(ddof=0)

1.4142135623730951

In [22]:
df['x_sc_sk']=(df['x']-3.0)/1.4142135623730951
df['x_sc_sk']

0   -1.414214
1   -0.707107
2    0.000000
3    0.707107
4    1.414214
Name: x_sc_sk, dtype: float64

**OR**

In [27]:
df['x_sc_sk']=(df['x']-df['x'].mean())/df['x'].std(ddof=0)
df['x_sc_sk']

0   -1.414214
1   -0.707107
2    0.000000
3    0.707107
4    1.414214
Name: x_sc_sk, dtype: float64

***Normalization***

min_max scaler=X-Xmin/Xmax-Xmin              Xmin=1,Xmax=5
X     
1    0          = 1-1/5-1  
2    0.25       = 2-1/5-1
3    0.5        = 3-1/5-1
4    0.75       = 4-1/5-1
5    1          = 5-1/5-1

***MinMax scaling using minmax scaler in sklearn***

In [37]:
from sklearn.preprocessing import MinMaxScaler
min_max= MinMaxScaler()
df['x_mm_sk']=min_max.fit_transform(df[['x']])
df['x_mm_sk']

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
Name: x_mm_sk, dtype: float64

***MinMax scaling using pandas***

In [40]:
df['x_mm_sk']=(df['x']-df['x'].min())/(df['x'].max()-df['x'].min())
df['x_mm_sk']

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
Name: x_mm_sk, dtype: float64

**FEATURE ENCODING**

convert descrete categorical to discret numeric
it is applied only on disrete categorical data

In [43]:
df1=pd.DataFrame({"shirtSize":["xl","large","medium","small"]})
df1

  shirtSize
0        xl
1     large
2    medium
3     small

***Ordinal Encoding***

In [54]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[["xl","large","medium","small"]])
df1["oe_shirtsize"]=oe.fit_transform(df1[['shirtSize']]).astype('int')
df1["oe_shirtsize"]

0    0
1    1
2    2
3    3
Name: oe_shirtsize, dtype: int32

***mapping***

In [57]:
df1["shirtsize_pandas"]=df1["shirtSize"].map({'small':0,'medium':1,'large':2,'xl':3})
df1["shirtsize_pandas"]

0    3
1    2
2    1
3    0
Name: shirtsize_pandas, dtype: int64

***Replace***

In [60]:
df1["shirtsize_pandas"]=df1["shirtSize"].replace({'small':0,'medium':1,'large':2,'xl':3})
df1["shirtsize_pandas"]

0    3
1    2
2    1
3    0
Name: shirtsize_pandas, dtype: int64

***Nominal Encoding  or dummy encoding***

In [9]:
import pandas as pd
df2=pd.DataFrame({'city':['H','B','M','B','D']})
df2

  city
0    H
1    B
2    M
3    B
4    D

In [80]:
pd.get_dummies(df2['city'],dtype=int)

   B  D  H  M
0  0  0  1  0
1  1  0  0  0
2  0  0  0  1
3  1  0  0  0
4  0  1  0  0

***Lable Encoding***

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df2['city_le']=le.fit_transform(df2['city'])
df2['city_le']

0    2
1    0
2    3
3    0
4    1
Name: city_le, dtype: int32

**FEATURE TRANSFORMATION**

*Converting skewed data to normal distribution data of a continus variable
*The normal distributon is lies between -1 to +1
*The value is more than +1 right skewed
*The value is less than -1 left skewed

In [63]:
import numpy as np
import pandas as pd
df=pd.read_csv("C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\stroke prediction.csv")
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,30669,Male,3.0,0,0,No,children,Rural,95.12,18.0,NaN,0
1,30468,Male,58.0,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0
3,56543,Female,70.0,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0
4,46136,Male,14.0,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
43395,56196,Female,10.0,0,0,No,children,Urban,58.64,20.4,never smoked,0
43396,5450,Female,56.0,0,0,Yes,Govt_job,Urban,213.61,55.4,formerly smoked,0
43397,28375,Female,82.0,1,0,Yes,Private,Urban,91.94,28.9,formerly smoked,0
43398,27973,Male,40.0,0,0,Yes,Private,Urban,99.16,33.2,never smoked,0
43399,36271,Female,82.0,0,0,Yes,Private,Urban,79.48,20.6,never smoked,0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43400 entries, 0 to 43399
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 43400 non-null  int64
 1   gender             43400 non-null  object
 2   age                43400 non-null  float64
 3   hypertension       43400 non-null  int64
 4   heart_disease      43400 non-null  int64
 5   ever_married       43400 non-null  object
 6   work_type          43400 non-null  object
 7   Residence_type     43400 non-null  object
 8   avg_glucose_level  43400 non-null  float64
 9   bmi                41938 non-null  float64
 10  smoking_status     30108 non-null  object
 11  stroke             43400 non-null  int64
dtypes: float64(3), int64(4), object(5)
memory usage: 4.0+ MB

In [41]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [ ]:
contineous=[ 'age','avg_glucose_level','bmi',]
discrete_categorical=['id', 'gender',  'hypertension', 'heart_disease', 'ever_married','work_type', 'Residence_type','smoking_status', 'stroke']

In [52]:
df['age'].skew()

-0.10249737146133675

In [54]:
df['bmi'].skew()

0.8987282500249906

In [58]:
df['avg_glucose_level'].skew()     #right skewed

1.6754049014377763

***Log transformation***

*Convert each value as log value
*Before apply the log check the minimum value,if it is not 0 than apply
*If it has 0 add each value with 0.0001(some negligency value).

In [71]:
df['avg_log']=np.log(df['avg_glucose_level'])
df['avg_log']

0        4.555139
1        4.476882
2        4.708539
3        4.234686
4        5.083142
           ...
43395    4.071417
43396    5.364152
43397    4.521136
43398    4.596735
43399    4.375505
Name: avg_log, Length: 43400, dtype: float64

In [67]:
np.log(df['avg_glucose_level']+0.0001)

0        4.555140
1        4.476883
2        4.708540
3        4.234687
4        5.083143
           ...
43395    4.071419
43396    5.364152
43397    4.521137
43398    4.596736
43399    4.375507
Name: avg_glucose_level, Length: 43400, dtype: float64

In [75]:
df['avg_log'].skew()           # converted to normal distribution

0.9325457821038275

***Root Transformation***

In [80]:
df['root_agl']=df['avg_glucose_level']**(1/2)
df['root_agl']

0         9.752948
1         9.378699
2        10.530432
3         8.309031
4        12.699606
           ...
43395     7.657676
43396    14.615403
43397     9.588535
43398     9.957911
43399     8.915156
Name: root_agl, Length: 43400, dtype: float64

In [84]:
df['root_agl'].skew()    #still it has skewness

1.3184435216491535

In [86]:
df['root_agl']=df['avg_glucose_level']**(1/12)
df['root_agl']

0        1.461692
1        1.452191
2        1.480498
3        1.423175
4        1.527443
           ...
43395    1.403943
43396    1.563634
43397    1.457556
43398    1.466768
43399    1.439975
Name: root_agl, Length: 43400, dtype: float64

In [93]:
df['root_agl'].skew() #Now the data iis normally distributed

0.9983431560256403

***Box-Cox***

In [99]:
from scipy.stats import boxcox

In [103]:
#Transform training data and save lambada value
df['agl_boxcox'],param=boxcox(df['avg_glucose_level'])
df['agl_boxcox']

0        0.914699
1        0.914117
2        0.915706
3        0.911969
4        0.917562
           ...
43395    0.910168
43396    0.918534
43397    0.914452
43398    0.914989
43399    0.913286
Name: agl_boxcox, Length: 43400, dtype: float64

In [107]:
df['agl_boxcox'].skew()   #data is normally distributed

0.06694113303235474