**Descriptive statistics**

*Using numpy*

import numpy as np

In [3]:
x=np.array([154,139,192,154,180,140,154,155,192])
x

array([154, 139, 192, 154, 180, 140, 154, 155, 192])

**sum**

In [5]:
np.sum(x)

1460

In [7]:
x.sum()

1460

**min**

In [11]:
np.min(x)

139

In [13]:
x.min()

139

**max**

In [16]:
np.max(x)

192

In [18]:
x.max()

192

**Mean**

In [23]:
np.sum(x)/len(x)

162.22222222222223

In [20]:
x.mean()

162.22222222222223

**Median**

In [28]:
np.median(x)

154.0

**Mode**

In [36]:
from scipy.stats import mode

In [42]:
mode(x)

C:\Users\Asus\AppData\Local\Temp\ipykernel_8564\1889230883.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode(x)

ModeResult(mode=array([154]), count=array([3]))

In [44]:
np.argmin(x)

1

In [46]:
np.argmax(x)

2

**Range**

In [49]:
x.max()-x.min()

53

**mean absolute deviation**

In [56]:
x=np.array([5,9,16,17,18])
deviation=x-x.mean()
deviation

array([-8., -4.,  3.,  4.,  5.])

In [58]:
abs_deviation=abs(deviation)
abs_deviation

array([8., 4., 3., 4., 5.])

In [60]:
np.mean(abs_deviation)

4.8

**variance/mean square deviation**

In [69]:
x=np.array([5,9,16,17,18])
deviation=x-x.mean()
square_deviation=deviation*deviation
square_deviation.mean()

26.0

In [71]:
np.var(x)

26.0

**Standerd deviation**

In [76]:
#option1
var =np.var(x)
std_deviation=np.sqrt(var)
std_deviation

5.0990195135927845

In [78]:
#option 2
np.std(x)

5.0990195135927845

**Deviation/sample variance**

In [81]:
s=np.array([2398,1844,1539,1311])
sample_variance=np.var(s)*len(s)/len(s)-1
sample_variance

165965.5

****sample standerd deviation****

In [90]:
sample_standerd_deviation=np.sqrt(sample_variance)
sample_standerd_deviation

407.3886350893947

**Percentile**

In [93]:
ages=[5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,37,61,31]
np.percentile(ages,25)

11.0

In [95]:
np.percentile(ages,75)

43.0

*Using Pandas*

In [12]:
import pandas as pd
df=pd.read_excel("C:\\Users\\Asus\\OneDrive\\Desktop\\liver.xlsx")
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [14]:
df.head()

   Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0   65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1   62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2   62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3   58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4   72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1

In [109]:
df['Age'].sum()

26087

In [113]:
df['Age'].min()

4

In [115]:
df['Age'].max()

90

In [117]:
df['Age'].mean()

44.74614065180103

In [119]:
df['Age'].median()

45.0

In [121]:
df['Age'].mode()

0    60
Name: Age, dtype: int64

**Overall descriptive statistics**

In [123]:
df.describe()

,Age,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
count,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,579.000000,583.000000
mean,44.746141,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947064,0.713551
std,16.189833,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.319592,0.452490
min,4.000000,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,0.000000
25%,33.000000,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000,0.000000
50%,45.000000,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.930000,1.000000
75%,58.000000,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000,1.000000
max,90.000000,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,1.000000

In [126]:
df.describe(include='all')

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
count,583.000000,583,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,579.000000,583.000000
unique,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,44.746141,NaN,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947064,0.713551
std,16.189833,NaN,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.319592,0.452490
min,4.000000,NaN,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,0.000000
25%,33.000000,NaN,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000,0.000000
50%,45.000000,NaN,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.930000,1.000000
75%,58.000000,NaN,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000,1.000000
max,90.000000,NaN,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,1.000000

**Range**

In [129]:
def Range_cal(data):
    min_val=min(data)
    max_val=max(data)
    return max_val-min_val
Range_cal(df['Age'])

86

**calculating probability using Z_Scrore technique**

In [22]:
from scipy import stats
stats.norm.cdf(0.9)

0.8159398746532405

In [26]:
stats.norm.ppf(0.8159398746532405)

0.8999999999999999

**Question:The normal distribution data with  mean of 70 & standerd deviation is 10.approximately what is the area contained between 70 and 90**

In [37]:
from scipy import stats
z_score70=(70-70)/10
z_score70

0.0

In [35]:
#probability from 0 to 70
stats.norm.cdf(0)

0.5

In [39]:
z_score90=(90-70)/10
z_score90

2.0

In [41]:
#probability from 0 to 90
stats.norm.cdf(2)

0.9772498680518208

In [43]:
#Arera contained between 70 to 90
#probability of 0 to 90-probality of 0 to 70
0.9772498680518208-0.5

0.4772498680518208

**Covarience**

In [46]:
import pandas as pd
df=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,0]})
df

   x  y
0  1  6
1  2  7
2  3  8
3  4  9
4  5  0

In [48]:
df.cov()

     x     y
x  2.5  -2.5
y -2.5  12.5