# 1.Example

In [3]:
import pandas as pd
df=pd.DataFrame({'in':[1,2,3,4,5],'out':[6,7,8,9,10]})
df

   in  out
0   1    6
1   2    7
2   3    8
3   4    9
4   5   10

# Select X(Input) & y(Output)

In [6]:
X=df[['in']] # X should be dataframe
y=df['out'] # y should be series

# Modelling

In [11]:
#import
from sklearn.linear_model import LinearRegression
#save in a model
model=LinearRegression()
#fit on data
model.fit(X,y)    #what will calculate ,How will

LinearRegression()

In [13]:
model.coef_

array([1.])

In [15]:
model.intercept_

5.0

# Prediction

In [18]:
model.predict(X)

array([ 6.,  7.,  8.,  9., 10.])

In [24]:
#substite X value in model(equation)
ypred=model.predict(X)
ypred

array([ 6.,  7.,  8.,  9., 10.])

# Evalvation

In [33]:
from sklearn.metrics import mean_squared_error
#mean_squared_error(actual value,predicted vale)
mean_squared_error(y,ypred)

0.0

In [35]:
mse=mean_squared_error(y,ypred)
mse

0.0

In [39]:
from math import sqrt
rmse=sqrt(mse)
rmse

0.0

In [41]:
print("RMSE of this model is:",rmse)

RMSE of this model is: 0.0

# 2.Example

In [53]:
import pandas as pd
df1=pd.DataFrame({'in':[10,20,30,40,50],'out':[20,15,10,5,0]})
df1

   in  out
0  10   20
1  20   15
2  30   10
3  40    5
4  50    0

In [55]:
X=df1[['in']] # X should be dataframe
y=df1['out'] # y should be series

In [57]:
#import
from sklearn.linear_model import LinearRegression
#save in a model
model=LinearRegression()
#fit on data
model.fit(X,y)    #what will calculate ,How will

LinearRegression()

In [59]:
model.coef_

array([-0.5])

In [61]:
model.intercept_

25.0

In [63]:
#substite X value in model(equation)
ypred=model.predict(X)
ypred

array([20., 15., 10.,  5.,  0.])

In [65]:
from sklearn.metrics import mean_squared_error
#mean_squared_error(actual value,predicted vale)
mean_squared_error(y,ypred)

0.0

In [67]:
mse=mean_squared_error(y,ypred)
mse

0.0

In [69]:
from math import sqrt
rmse=sqrt(mse)
rmse

0.0

In [71]:
print("RMSE of this model is:",rmse)

RMSE of this model is: 0.0