In [ ]:
import numpy as np
import pandas as pd

**pandas series**

**creating series using list**

In [12]:
import pandas as pd
l=[1,2,3,4,5,6]
s=pd.Series(l)
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

**creating series using array**

In [19]:
import numpy as np
n=np.array([1,2,34,5,6])
s=pd.Series(n)
s

0     1
1     2
2    34
3     5
4     6
dtype: int32

**creating series using dictionary**

In [25]:
d1={'a':1,'b':2,'c':3}
s1=pd.Series(d1)
s1

a    1
b    2
c    3
dtype: int64

In [27]:
d2={'a':[1,2,3,4,5],'b':[1,3,5,7,9],'c':[2,4,6,8,0]}
s2=pd.Series(d2)
s2

a    [1, 2, 3, 4, 5]
b    [1, 3, 5, 7, 9]
c    [2, 4, 6, 8, 0]
dtype: object

**pandas DataFrame**

**creating dataframe using dictionary**

In [34]:
df1={'col1':[1,2],'col2':[3,4]}
df1=pd.DataFrame(df1)
df1

   col1  col2
0     1     3
1     2     4

In [36]:
tempreture_df=pd.DataFrame({'city':['mumbai','pune','chennai','kolkata','Banglore'],'tempreture':[23,34,56,32,45]})
tempreture_df

       city  tempreture
0    mumbai          23
1      pune          34
2   chennai          56
3   kolkata          32
4  Banglore          45

In [38]:
tempreture_df.shape

(5, 2)

In [40]:
tempreture_df.size

10

**Add column**

In [43]:
tempreture_df['Aqi']=[123,321,234,43,543]
tempreture_df

       city  tempreture  Aqi
0    mumbai          23  123
1      pune          34  321
2   chennai          56  234
3   kolkata          32   43
4  Banglore          45  543

In [45]:
humidity_df=pd.DataFrame({'city':['mumbai','pune','hydrabad','Banglore','kolkata'],'humidity':[12,21,32,3,4]})
humidity_df

       city  humidity
0    mumbai        12
1      pune        21
2  hydrabad        32
3  Banglore         3
4   kolkata         4

**combining the dataframes**
--using two methods--
--append method--
--concat method--

In [48]:
df1=tempreture_df.append(humidity_df)
df1

C:\Users\Asus\AppData\Local\Temp\ipykernel_2216\3534334679.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=tempreture_df.append(humidity_df)

       city  tempreture    Aqi  humidity
0    mumbai        23.0  123.0       NaN
1      pune        34.0  321.0       NaN
2   chennai        56.0  234.0       NaN
3   kolkata        32.0   43.0       NaN
4  Banglore        45.0  543.0       NaN
0    mumbai         NaN    NaN      12.0
1      pune         NaN    NaN      21.0
2  hydrabad         NaN    NaN      32.0
3  Banglore         NaN    NaN       3.0
4   kolkata         NaN    NaN       4.0

In [50]:
df1=tempreture_df.append(humidity_df,ignore_index=True)
df1

C:\Users\Asus\AppData\Local\Temp\ipykernel_2216\2228493912.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1=tempreture_df.append(humidity_df,ignore_index=True)

       city  tempreture    Aqi  humidity
0    mumbai        23.0  123.0       NaN
1      pune        34.0  321.0       NaN
2   chennai        56.0  234.0       NaN
3   kolkata        32.0   43.0       NaN
4  Banglore        45.0  543.0       NaN
5    mumbai         NaN    NaN      12.0
6      pune         NaN    NaN      21.0
7  hydrabad         NaN    NaN      32.0
8  Banglore         NaN    NaN       3.0
9   kolkata         NaN    NaN       4.0

In [56]:
df=pd.concat([tempreture_df,humidity_df],ignore_index=True)
df

       city  tempreture    Aqi  humidity
0    mumbai        23.0  123.0       NaN
1      pune        34.0  321.0       NaN
2   chennai        56.0  234.0       NaN
3   kolkata        32.0   43.0       NaN
4  Banglore        45.0  543.0       NaN
5    mumbai         NaN    NaN      12.0
6      pune         NaN    NaN      21.0
7  hydrabad         NaN    NaN      32.0
8  Banglore         NaN    NaN       3.0
9   kolkata         NaN    NaN       4.0

**merging the dataframes**

In [60]:
dg=pd.merge(tempreture_df,humidity_df,on='city',how='inner')
dg

       city  tempreture  Aqi  humidity
0    mumbai          23  123        12
1      pune          34  321        21
2   kolkata          32   43         4
3  Banglore          45  543         3

In [62]:
dh=pd.merge(tempreture_df,humidity_df,on='city',how='outer')
dh

       city  tempreture    Aqi  humidity
0    mumbai        23.0  123.0      12.0
1      pune        34.0  321.0      21.0
2   chennai        56.0  234.0       NaN
3   kolkata        32.0   43.0       4.0
4  Banglore        45.0  543.0       3.0
5  hydrabad         NaN    NaN      32.0

**Drop columns from the dataframes**

In [74]:
df=tempreture_df.drop(columns=['city','Aqi'])
df

   tempreture
0          23
1          34
2          56
3          32
4          45

In [76]:
df=tempreture_df.drop(columns=['city'])
df

   tempreture  Aqi
0          23  123
1          34  321
2          56  234
3          32   43
4          45  543